### ISSUE TITLE
simple export feature (for articles only)

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/CommunityDashboard#20]
add export feature.

not having it - seems to be not in the spirit of OHDSI

**Comment by natb1** [comment]
Hi @vojtechhuser My personal opinion on this is that if programmatic access to the data is desired then we can facilitate that through PR's to the open source repo. The API for "exporting" data already exists as part of the supported code base. The data is more complex than something that could be squished into a CSV, for example, and enabling access through PR's gives us some ability to mitigate, for example, an errant data science script that could affect the performance or cost to run the site.

**Comment by vojtechhuser** [comment]
>The API for "exporting" data already exists
Can you point me to it please. A smaller request would thus be a help link that would show folks how to export the data using API. The export of articles I have in mind is just CSV with pubmedIDs.

**Comment by natb1** [comment]
I think I understand, it makes sense.

When I say the API exists to get to the data I only meant that this repo IS that API. Code in a PR could get to the data the same way the rest of the site does.

I can try to think of a solution for your case. In isolation what you describe seems simple, but in general the main issue is that the site is unauthenticated. So if we put a button on there to download data it's probably only a matter of time before someone starts crushing it with their Spark cluster. Since this is a community sponsored site, we couldn't really handle that. Without authentication it's hard to mitigate that.

**Comment by natb1** [comment]
This might also be helpful: https://github.com/OHDSI/CommunityDashboard/blob/main/test/exports/all.json

As part of our development process we keep a raw export of some of the data in the repo for testing. I can't promise that data will always be complete or up to date, but it could at least get someone started working with the raw data.

**Comment by natb1** [comment]
We'll be logging data to the repo (link above) on a "somewhat regular" cadence and improving the quality of that data over time for anybody who wants to work with the raw data. Raw publication data is available there - I can provide more details for anybody interested. Feel free to re-open with additional thoughts/comments.
